### ISSUE TITLE
strange behaviour

### ISSUE THREAD

**Issue by revelt** [deltreey/wildstring#2]
hi all,

Please have a look (see it on [RunKit](https://runkit.com/58fd11151dc1c60013c79f85/58fd11151dc1c60013c79f86) as well):

    var wildstring = require("wildstring")
    var res = wildstring.match("*zz", "zzz")
    console.log('res = ' + res)
    // => "res = false"

Why is the `res` not `true`? I would expect that wildcard would "catch" the first `z`, then second and third would get matched exactly.

thank you.

**Comment by deltreey** [comment]
nice find!  I'll fix this tomorrow.

**Comment by deltreey** [comment]
version 1.0.9 released with this fix
